### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by galo4kin** [ilbuonmarcio/TurnipMaster#1]
Service does not work _ (
I`m doing something wrong?

```
(venv) bash-3.2$ python3 ./src/turnipexchange.py --name Username
[2020-04-20 20:04:53] Getting islands page...
[2020-04-20 20:04:07] Parsing page...
Traceback (most recent call last):
  File "./src/turnipexchange.py", line 245, in <module>
    islands = tex.get_islands()
  File "./src/turnipexchange.py", line 42, in get_islands
    name = island_top_note[0].findChild('h2').contents[0].strip()
TypeError: 'NoneType' object is not callable
```

**Comment by ilbuonmarcio** [comment]
Hi, thanks for the report!

Probably the content of the page we're scraping has changed since the last commit,
I'll try to fix it as soon as possible!

**Comment by galo4kin** [comment]
Thax a lot

**Comment by ilbuonmarcio** [comment]
Fixed as per commit d6b6c24ee5ff34d7c0cb3bec265aca37cbfb24f7 !

**Comment by galo4kin** [comment]
Thanx.
Today i have one more other error %( 
```
~/P/TurnipMaster (master ☡=) python3 src/turnipexchange.py --name Username
[2020-04-23 14:04:16] Getting islands page...
[2020-04-23 14:04:28] Parsing page...
[2020-04-23 14:04:28] Filtering by queue length (2) [0 <-> inf]
[2020-04-23 14:04:28] Filtering by turnips price (2) [0 <-> inf]
[2020-04-23 14:04:28] Ignoring fruit (2) [None]
[2020-04-23 14:04:28] Filtering by emisphere (2) [None]
[2020-04-23 14:04:28] Islands after filters: 2
[2020-04-23 14:04:28] Sorting islands by turnips price...
[2020-04-23 14:04:28] Skipping 0 islands starting from top...
[2020-04-23 14:04:28] USER: Username
[2020-04-23 14:04:28] MODE: sell
[2020-04-23 14:04:28] [code:24deee69][price:301][queue:0/20]
[2020-04-23 14:04:28] [code:48bd86ad][price:150][queue:0/25]
[2020-04-23 14:04:28] Opening the first island based on price...
Traceback (most recent call last):
  File "src/turnipexchange.py", line 259, in <module>
    tex.open_island(islands[0].code, name)
  File "src/turnipexchange.py", line 86, in open_island
    EC.visibility_of_any_elements_located((By.XPATH, "/html/body/div/div[2]/div[2]/div/input"))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by ilbuonmarcio** [comment]
As you can see in the Firefox browser tab opened by the application, the applications throws this error because he cannot join the queue due to it being already full after 10 seconds of trying.

We can decide to handle that, but it requires more work to be done and I don't think it will be worth the time spent on it.

Try using other filters like `--skip` and price and queue length for making sure you are going to be inserted in a free queue!
